
# Site settings

# NB! Set your site's url, otherwise stuff will break :)

url: "http://www.iainbenson.com"

# If you're hosting your site at a Project repository on GitHub pages
# (https://yourusername.github.io/repository-name)
# and NOT your user repository (https://yourusername.github.io)
# then add in the baseurl here, like this: "/repository-name"
#
# NB! Without this *nothing* will work, because it's used in every path :)

baseurl:

# Google tracking id
#google-tracking-id: "UA-96368179-1"
google-tracking-id:

# Forces https everywhere in your website, except when you serve it locally
# If you are not hosted on Github Pages, and your host doesn't support https
# then you should disable it

force-https: True

#############
# HTML Head #
#############

lang: "en"
author: "Iain Benson"
title: "iainbenson.com"
description: "Blog and website of Iain Benson" 
keywords: "benson, iain, personal, jekyll, theme"
favicon: "/img/favicon.ico"

################
# Header layout #
################

black-favicon:

background-img: "../img/intro-bg.jpg"

##############################
# Dynamic Text on the Header #
##############################

dynamic-typing: False
shuffle: True # Shuffle the lines.
loop: True
loop-count: False # Set False for infinite loop, or set any number for finite loop.
type-speed: 10
start-delay: 200
delete-delay: 5000
lines: # You can add HTML Tags in the Text
  - text: "If you can't dazzle them with brilliance, baffle them with bullshit"
  - text: "I have never let my schooling interfere with my education"
  - text: "In knowing that you know nothing, that makes you the smartest of all"
  - text: "The eyes only see what the mind is prepared to comprehend"
  
me-img: "/img/author.jpg"

##############################
# Color the browser elements #
##############################
color-browser: "#000000"
apple-status-bar-style: "black"

################
# Web app mode #
################

web-app-mode: True

# Icons for Web App mode

icon-36p: "/img/web-app/icon-36p.png"
icon-48p: "/img/web-app/icon-48p.png"
icon-72p: "/img/web-app/icon-72p.png"
icon-96p: "/img/web-app/icon-96p.png"
icon-144p: "/img/web-app/icon-144p.png"
icon-192p: "/img/web-app/icon-192p.png"

########
# Blog #
########

enable-gesture-navigation: True

post-preview-words: 20

paginate: 6

email-share: True
fb-share: True
twitter-share: True
linkedin-share: False
reddit-share: True
google-plus-share: False
tumblr-share: True
pinterest-share: True
pocket-share: True
vkontakte-share: False

disqus-shortname:

syntax-highlight: True

############
# Timeline #
############

events:
  - image: "/img/timeline/spain.jpg"
    date: "2009 - Today"
    description: "Freelance Programmer, working remotely from my underwater Spanish volcano.  Involved in Dev and Test."
  - image: "/img/timeline/linedata2.jpg"
    date: "2006 - 2009"
    description: "Analyst Programmer, Linedata Services. Fund Management Accounting Software, C, Oracle, Python."
  - image: "/img/timeline/eurofightersmall.jpg"
    date: "2001 - 2006"
    description: "Systems Engineer, BAE Systems. Dev of radar modes for Eurofighter Typhoon using C and GEDAE."
  - image: "/img/timeline/navysmall.jpg"
    date: "1998 - 2001"
    description: "Scientist, DERA.  Naval tactics. Investigating existence of transient signal in noise using Matlab."
  - image: "/img/timeline/deathstarsmall.jpg"
    date: "1996 - 1997"
    description: "Msc Opto-electronics at the University of Strathclyde."
  - image: "/img/timeline/glasgowuni.jpg"
    date: "1992 - 1996"
    description: "1st Class BSc (hons) in Physics at the University of Glasgow."  
  
# First image of the Timeline

timeline-img: "/img/timeline/monkey.jpg"

###########
# Contact #
###########

email: "&#105;&#097;&#105;&#110;&#098;&#101;&#110;&#115;&#111;&#110;@&#112;&#114;&#111;&#116;&#111;&#110;&#109;&#097;&#105;&#108;&#046;&#099;&#111;&#109;"

################
# Author Blurb #
################

# The author blurb goes underneath blog posts.
# This works best when your author blurb image has a transparent background, or matches your site background color.

# if the author_blurb is not set, then this feature is skipped
author_blurb: "Iain Benson is a person and not a grassy plant viking. He lives in Northern Spain. In his spare time, Iain likes tinkering with his Raspberry Pi, going for long walks and drinking wine.  Preferably all at the same time."
author_blurb_image: "/img/author.jpg"

##################
# Social Buttons #
##################

social:
  - title: "twitter"
    url: "https://twitter.com/iainbenson"
  - title: "github"
    url: "https://github.com/0x3F3F"
  - title: "rss"
    url: "/feed.xml"

############
# 404 page #
############

err-404-img: "/img/labtocat.png"

##################
# GPG on Keybase #
##################

keybase-username: iainbenson
keybase-in-social: False
keybase-in-footer: False

################################################################################

# NB! Tread carefully if you want to change the variables below this point!

# Sections shown in the index page

pages_list:
  About: 'about'
  Blog: 'latest-post'
  Timeline: 'timeline'
  Contact: 'contact'

# Exclusion list from the generated _site

exclude: ["LICENSE", "README.md", "CONTRIBUTING", "CONTRIBUTORS", "scripts"]

# Pagination path

paginate_path: "blog/page:num/"

# Enable minification SASS

sass:
  style: compressed

gems:
  - jekyll-paginate
  - jekyll-tagging
  - jemoji
