
# Site settings

# NB! Set your site's url, otherwise stuff will break :)

url: "http://iainbenson.com"

# If you're hosting your site at a Project repository on GitHub pages
# (https://yourusername.github.io/repository-name)
# and NOT your user repository (https://yourusername.github.io)
# then add in the baseurl here, like this: "/repository-name"
#
# NB! Without this *nothing* will work, because it's used in every path :)

baseurl:

# Google tracking id

google-tracking-id: ""

# Forces https everywhere in your website, except when you serve it locally
# If you are not hosted on Github Pages, and your host doesn't support https
# then you should disable it

force-https: False

#############
# HTML Head #
#############

lang: "en"
author: "Iain Benson"
title: "{ Iain Benson }"
description: "Blog and website of Iain Benson, blogging mainly for tech. Opinions expressed are mine."
keywords: "benson, iain, personal, jekyll, theme"
favicon: "/img/favicon.ico"

################
# Header layout #
################

black-favicon: "/img/black-lab-glass.ico"

background-img: "../img/intro-bg.jpg"

##############################
# Dynamic Text on the Header #
##############################

dynamic-typing: True
shuffle: True # Shuffle the lines.
loop: True
loop-count: False # Set False for infinite loop, or set any number for finite loop.
type-speed: 10
start-delay: 200
delete-delay: 5000
lines: # You can add HTML Tags in the Text
  - text: "The lower you fall, the higher you'll fly."
  - text: "Where’s your will to be weird?"

me-img: "/img/jetpacktocat.png"

##############################
# Color the browser elements #
##############################
color-browser: "#000000"
apple-status-bar-style: "black"

################
# Web app mode #
################

web-app-mode: True

# Icons for Web App mode

icon-36p: "/img/web-app/icon-36p.png"
icon-48p: "/img/web-app/icon-48p.png"
icon-72p: "/img/web-app/icon-72p.png"
icon-96p: "/img/web-app/icon-96p.png"
icon-144p: "/img/web-app/icon-144p.png"
icon-192p: "/img/web-app/icon-192p.png"

########
# Blog #
########

enable-gesture-navigation: True

post-preview-words: 20

paginate: 8

email-share: True
fb-share: True
twitter-share: True
linkedin-share: True
reddit-share: True
google-plus-share: True
tumblr-share: True
pinterest-share: True
pocket-share: True
vkontakte-share: True

disqus-shortname: "panossakkos"

syntax-highlight: True

############
# Timeline #
############

events:
  - image: "/img/timeline/spidertocat.png"
    date: "2009 - Today"
    description: "Independant programmer, Spain.  Involved in Dev and Test for Linedata Limited."
  - image: "/img/timeline/baracktocat.jpg"
    date: "2006 - 2009"
    description: "Analyst Porgrammer, Linedata Services. Accounting Software, Fund Managers, City of London, 'nuf said."
  - image: "/img/timeline/baracktocat.jpg"
    date: "2001 - 2006"
    description: "Systems Engineer, BAE systems. Involved dev of radar modes for Eurofighter Typhoon"
  - image: "/img/timeline/baracktocat.jpg"
    date: "1998 - 2001"
    description: "Scientist, DERA.  Investigating existance of transient signal in noise using Matlab"
  - image: "/img/timeline/baracktocat.jpg"
    date: "1996 - 1997"
    description: "Msc Opto-electronics at University of Strathclyde"
  - image: "/img/timeline/baracktocat.jpg"
    date: "1992 - 1996"
    description: "1st Class BSc (hons) in Physics at University of Glasgow"  
  
# First image of the Timeline

timeline-img: "/img/timeline/default.png"

###########
# Contact #
###########

email: "1a1n_b3ns0n@gmail.com"

################
# Author Blurb #
################

# The author blurb goes underneath blog posts.
# This works best when your author blurb image has a transparent background, or matches your site background color.

# if the author_blurb is not set, then this feature is skipped
author_blurb: "Iain Benson is an awesome person. He lives in Spain, where he works as an independant contractor. In his spare time, Iain likes tinkering with his Raspberry Pi and going for long walks."
author_blurb_image: "/img/author.png"

##################
# Social Buttons #
##################

social:
  - title: "twitter"
    url: "https://twitter.com/iainbenson"
  - title: "github"
    url: "https://github.com/0x3F3F"
  - title: "bitcoin"
    url: "https://blockchain.info/address/1LHuKC9Em3KA5yoZaf7nngnNdf9K7s2gSi"
  - title: "rss"
    url: "/feed.xml"

############
# 404 page #
############

err-404-img: "/img/labtocat.png"

##################
# GPG on Keybase #
##################

keybase-username: iainbenson
keybase-in-social: False
keybase-in-footer: False

################################################################################

# NB! Tread carefully if you want to change the variables below this point!

# Sections shown in the index page

pages_list:
  About: 'about'
  Blog: 'latest-post'
  Timeline: 'timeline'
  Contact: 'contact'

# Exclusion list from the generated _site

exclude: ["LICENSE", "README.md", "CONTRIBUTING", "CONTRIBUTORS", "scripts"]

# Pagination path

paginate_path: "blog/page:num/"

# Enable minification SASS

sass:
  style: compressed

gems:
  - jekyll-paginate
  - jemoji
